name: optimism_service
author: valory
version: 0.1.0
description: An optimism liquidity trader service.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: valory/optimism_agent:0.1.0:bafybeias67zqlnl7feagcwnab7slt5xm4tsbovvz34r3zjab2psc6t3dvu
number_of_agents: 4
deployment:
  agent:
    ports:
      0:
        8000: 8000
      1:
        8001: 8000
      2:
        8002: 8000
      3:
        8003: 8000
---
public_id: valory/superagent_abci:0.1.0
type: skill
extra:
  params_args:
    args:
      setup: &id001
        all_participants: ${ALL_PARTICIPANTS:list:[]}
        consensus_threshold: null
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:0x0000000000000000000000000000000000000000}
      genesis_config: &id002
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
0:
  models:
    benchmark_tool:
      args:
        log_dir: ${LOG_DIR:str:/logs}
    params:
      args:
        setup: *id001
        genesis_config: *id002
        cleanup_history_depth: 1
        cleanup_history_depth_current: null
        drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
        earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
        keeper_timeout: 30.0
        max_attempts: 10
        max_healthcheck: 120
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
        retry_attempts: 400
        retry_timeout: 3
        request_retry_delay: 1.0
        request_timeout: 10.0
        round_timeout_seconds: 30.0
        service_id: superagent
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: 1
        tendermint_check_sleep_delay: 3
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: 5
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:optimism_tm_0:26656}
        tx_timeout: 10.0
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: 1205
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://optimism.autonolas.tech/}
        multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
        ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
        default_chain_id: ${DEFAULT_CHAIN_ID:str:ethereum}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:34088325}
        allowed_lp_pool_addresses: ${ALLOWED_LP_POOL_ADDRESSES:str:{"balancer":{"ethereum":["0x3de27EFa2F1AA663Ae5D458857e731c129069F29"],"arbitrum":["0x32dF62dc3aEd2cD6224193052Ce665DC18165841"]},"velodrome":{"optimism":["0xF4F2657AE744354bAcA871E56775e5083F7276Ab"]}}}
        allowed_assets: ${ALLOWED_ASSETS:str:"{"ethereum":{"eth":"0x0000000000000000000000000000000000000000","weth":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","usdc":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"},"optimism":{"usdc":"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85","dai":"0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"}}"}
        safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","arbitrum":"0x0000000000000000000000000000000000000000","optimism":"0x0000000000000000000000000000000000000000"}}
        pool_data_api_url: ${POOL_DATA_API_URL:str:"https://api.merkl.xyz/v3/campaigns?chainIds=42161&live=true&types=1"}
        allowed_chains: ${ALLOWED_CHAINS:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        gas_reserve: ${GAS_RESERVE:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        round_threshold: ${ROUND_THRESHOLD:int:5}
        apr_threshold: ${APR_THRESHOLD:int:5}
        min_balance_multiplier: ${MIN_BALANCE_MULTIPLIER:int:5}
1:
  models:
    benchmark_tool:
      args:
        log_dir: ${LOG_DIR:str:/logs}
    params:
      args:
        setup: *id001
        genesis_config: *id002
        cleanup_history_depth: 1
        cleanup_history_depth_current: null
        drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
        earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
        keeper_timeout: 30.0
        max_attempts: 10
        max_healthcheck: 120
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
        retry_attempts: 400
        retry_timeout: 3
        request_retry_delay: 1.0
        request_timeout: 10.0
        round_timeout_seconds: 30.0
        service_id: superagent
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: 1
        tendermint_check_sleep_delay: 3
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: 5
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:optimism_tm_0:26656}
        tx_timeout: 10.0
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: 1205
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://optimism.autonolas.tech/}
        multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
        ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
        default_chain_id: ${DEFAULT_CHAIN_ID:str:ethereum}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:34088325}
        allowed_lp_pool_addresses: ${ALLOWED_LP_POOL_ADDRESSES:str:{"balancer":{"ethereum":["0x3de27EFa2F1AA663Ae5D458857e731c129069F29"],"arbitrum":["0x32dF62dc3aEd2cD6224193052Ce665DC18165841"]},"velodrome":{"optimism":["0xF4F2657AE744354bAcA871E56775e5083F7276Ab"]}}}
        allowed_assets: ${ALLOWED_ASSETS:str:"{"ethereum":{"eth":"0x0000000000000000000000000000000000000000","weth":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","usdc":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"},"optimism":{"usdc":"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85","dai":"0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"}}"}
        safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","arbitrum":"0x0000000000000000000000000000000000000000","optimism":"0x0000000000000000000000000000000000000000"}}
        pool_data_api_url: ${POOL_DATA_API_URL:str:"https://api.merkl.xyz/v3/campaigns?chainIds=42161&live=true&types=1"}
        allowed_chains: ${ALLOWED_CHAINS:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        gas_reserve: ${GAS_RESERVE:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        round_threshold: ${ROUND_THRESHOLD:int:5}
        apr_threshold: ${APR_THRESHOLD:int:5}
        min_balance_multiplier: ${MIN_BALANCE_MULTIPLIER:int:5}
2:
  models:
    benchmark_tool:
      args:
        log_dir: ${LOG_DIR:str:/logs}
    params:
      args:
        setup: *id001
        genesis_config: *id002
        cleanup_history_depth: 1
        cleanup_history_depth_current: null
        drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
        earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
        keeper_timeout: 30.0
        max_attempts: 10
        max_healthcheck: 120
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
        retry_attempts: 400
        retry_timeout: 3
        request_retry_delay: 1.0
        request_timeout: 10.0
        round_timeout_seconds: 30.0
        service_id: superagent
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: 1
        tendermint_check_sleep_delay: 3
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: 5
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:optimism_tm_0:26656}
        tx_timeout: 10.0
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: 1205
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://optimism.autonolas.tech/}
        multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
        ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
        default_chain_id: ${DEFAULT_CHAIN_ID:str:ethereum}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:34088325}
        allowed_lp_pool_addresses: ${ALLOWED_LP_POOL_ADDRESSES:str:{"balancer":{"ethereum":["0x3de27EFa2F1AA663Ae5D458857e731c129069F29"],"arbitrum":["0x32dF62dc3aEd2cD6224193052Ce665DC18165841"]},"velodrome":{"optimism":["0xF4F2657AE744354bAcA871E56775e5083F7276Ab"]}}}
        allowed_assets: ${ALLOWED_ASSETS:str:"{"ethereum":{"eth":"0x0000000000000000000000000000000000000000","weth":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","usdc":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"},"optimism":{"usdc":"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85","dai":"0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"}}"}
        safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","arbitrum":"0x0000000000000000000000000000000000000000","optimism":"0x0000000000000000000000000000000000000000"}}
        pool_data_api_url: ${POOL_DATA_API_URL:str:"https://api.merkl.xyz/v3/campaigns?chainIds=42161&live=true&types=1"}
        allowed_chains: ${ALLOWED_CHAINS:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        gas_reserve: ${GAS_RESERVE:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        round_threshold: ${ROUND_THRESHOLD:int:5}
        apr_threshold: ${APR_THRESHOLD:int:5}
        min_balance_multiplier: ${MIN_BALANCE_MULTIPLIER:int:5}
3:
  models:
    benchmark_tool:
      args:
        log_dir: ${LOG_DIR:str:/logs}
    params:
      args:
        setup: *id001
        genesis_config: *id002
        cleanup_history_depth: 1
        cleanup_history_depth_current: null
        drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
        earliest_block_to_monitor: ${EARLIEST_BLOCK_TO_MONITOR:int:8053690}
        keeper_timeout: 30.0
        max_attempts: 10
        max_healthcheck: 120
        multisend_address: ${MULTISEND_ADDRESS:str:0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761}
        termination_sleep: ${TERMINATION_SLEEP:int:900}
        reset_pause_duration: ${RESET_PAUSE_DURATION:int:300}
        on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
        reset_tendermint_after: ${RESET_TENDERMINT_AFTER:int:30}
        retry_attempts: 400
        retry_timeout: 3
        request_retry_delay: 1.0
        request_timeout: 10.0
        round_timeout_seconds: 30.0
        service_id: superagent
        service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:0x48b6af7B12C71f09e2fC8aF4855De4Ff54e775cA}
        share_tm_config_on_startup: ${USE_ACN:bool:false}
        sleep_time: 1
        tendermint_check_sleep_delay: 3
        tendermint_com_url: ${TENDERMINT_COM_URL:str:http://localhost:8080}
        tendermint_max_retries: 5
        tendermint_url: ${TENDERMINT_URL:str:http://localhost:26657}
        tendermint_p2p_url: ${TENDERMINT_P2P_URL_0:str:optimism_tm_0:26656}
        tx_timeout: 10.0
        use_termination: ${USE_TERMINATION:bool:false}
        validate_timeout: 1205
        service_endpoint_base: ${SERVICE_ENDPOINT_BASE:str:https://optimism.autonolas.tech/}
        multisend_batch_size: ${MULTISEND_BATCH_SIZE:int:5}
        ipfs_address: ${IPFS_ADDRESS:str:https://gateway.autonolas.tech/ipfs/}
        default_chain_id: ${DEFAULT_CHAIN_ID:str:ethereum}
        termination_from_block: ${TERMINATION_FROM_BLOCK:int:34088325}
        allowed_lp_pool_addresses: ${ALLOWED_LP_POOL_ADDRESSES:str:{"balancer":{"ethereum":["0x3de27EFa2F1AA663Ae5D458857e731c129069F29"],"arbitrum":["0x32dF62dc3aEd2cD6224193052Ce665DC18165841"]},"velodrome":{"optimism":["0xF4F2657AE744354bAcA871E56775e5083F7276Ab"]}}}
        allowed_assets: ${ALLOWED_ASSETS:str:"{"ethereum":{"eth":"0x0000000000000000000000000000000000000000","weth":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","usdc":"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"},"optimism":{"usdc":"0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85","dai":"0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"}}"}
        safe_contract_addresses: ${SAFE_CONTRACT_ADDRESSES:str:{"ethereum":"0x0000000000000000000000000000000000000000","arbitrum":"0x0000000000000000000000000000000000000000","optimism":"0x0000000000000000000000000000000000000000"}}
        pool_data_api_url: ${POOL_DATA_API_URL:str:"https://api.merkl.xyz/v3/campaigns?chainIds=42161&live=true&types=1"}
        allowed_chains: ${ALLOWED_CHAINS:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        gas_reserve: ${GAS_RESERVE:str:{"ethereum":1,"optimism":10,"arbitrum":42161}}
        round_threshold: ${ROUND_THRESHOLD:int:5}
        apr_threshold: ${APR_THRESHOLD:int:5}
        min_balance_multiplier: ${MIN_BALANCE_MULTIPLIER:int:5}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${ETHEREUM_LEDGER_RPC:str:https://virtual.mainnet.rpc.tenderly.co/85a9fd10-356e-4526-b1f6-7148366bf227}
      chain_id: ${ETHEREUM_LEDGER_CHAIN_ID:int:1}
      poa_chain: ${ETHEREUM_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${ETHEREUM_LEDGER_PRICING:str:eip1559}
    arbitrum:
      address: ${ARBITRUM_LEDGER_RPC:str:https://virtual.arbitrum.rpc.tenderly.co/8973f254-1594-4a82-8e26-25a10a01bf46}
      chain_id: ${ARBITRUM_LEDGER_CHAIN_ID:int:42161}
      poa_chain: ${ARBITRUM_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${ARBITRUM_LEDGER_PRICING:str:eip1559}
    bnb:
      address: ${BNB_LEDGER_RPC:str:https://virtual.arbitrum.rpc.tenderly.co/8973f254-1594-4a82-8e26-25a10a01bf46}
      chain_id: ${BNB_LEDGER_CHAIN_ID:int:42161}
      poa_chain: ${BNB_LEDGER_IS_POA_CHAIN:bool:false}
      default_gas_price_strategy: ${BNB_LEDGER_PRICING:str:eip1559}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${ACN_URI:str:acn.staging.autonolas.tech:9005}
    public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${ACN_NODE_PUBLIC_KEY:str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
